spring.datasource:
  url: "jdbc:postgresql://localhost:5432/ProjectManagement"
  username: "postgres"
  password: "postgres"
  driver-class-name: org.postgresql.Driver
  properties:
    hibernate:
      id:
        new_generator_mappings=false
  hikari:
    connection-timeout: 10000
    validation-timeout: 10000
    idle-timeout: 10000
    leak-detection-threshold: 10000
    max-lifetime: 3600000
    max-pool-size: 2
    min-idle: 1000
    is-auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



